### PR TITLE
WSSRV001, 002 and 003

### PR DESCRIPTION
**Pull request by damianscoles**
Combined WSSRV001, WSSRV002 and WSSRV003 tests.

### CODE REVIEW

**Comment by cunninghamp** [comment]
One PR per test will be better in future, allowing us to have conversations about each test individually, and accept or roll back each PR individually.

PRs should also merge to development, not master.

Reference URLs in Tests.xml are no longer required with the new standardised Wiki documentation for tests. They can be removed.

Please also add some more commenting and verbose output. One of those tests has good comments throughout, but all three are missing any Write-Verbose output.

For disk space, should we be checking C: or checking the Exchange install volume? That can be pulled from the registry. $env:exchangeinstallpath returns it for the local server but you can query it from the registry for remote servers ([example here](http://exchangeserverpro.com/get-exchange-install-path-using-powershell/)).

**Comment by damianscoles** [comment]
Disk space was referenced in the test requirements of the test.  If we want to specifically target the Exchange installation drive, we can do this as well.  The C drive tests were only specific to the C drive and were not to be related to where Exchange is installed.

Ok on separating the tests.  These were just developed in a bunch.

I will add more comments for consistency.  I will also ass Write-Verbose.

Want me to pull this one back and put in three separate ones?  I can do that with no problem t make it easier for commenting.

**Comment by damianscoles** [comment]
Added verbose information.  Added comments.  Let me know if you want me to pull and put back up as three separate requests.  I can also attach it to the Dev branch as well.

**Comment by cunninghamp** [comment]
Yes, you'll need to close this PR without merging and do new ones to development branch, so you may as well do separate ones then anyway.

**Pull request closed without merging**
