### PR TITLE
Added AD Domain Check

### PR DESCRIPTION
**Pull request by damianscoles**
Checks if Active Directory Domains are Windows 2008 +

### CODE REVIEW

**Comment by damianscoles** [comment]
Not sure what happened there.  I closed the one request and then created a Pull request for development.

**Comment by cunninghamp** [comment]
Refer to issue 34
https://github.com/cunninghamp/ExchangeAnalyzer/issues/34

**Comment by damianscoles** [comment]
In progress.  Testing code now.

**Comment by damianscoles** [comment]
OK.  Changes Added.

**Comment by cunninghamp** [comment]
Updated branch with latest development updates. Tested in my lab and made some minor changes to test comments.

@damianscoles does this handle multiple domains? Should this line:

```
$ADDomain = Get-ADDomain -ErrorAction STOP
```

be

```
$ADDomains = @(Get-ADDomain -ErrorAction STOP)
```

And then have test AD001 loop through? Eg,

```
foreach ($ADDomain in $ADDomains)
```

I do not have a multi-domain forest to test against.

**Comment by damianscoles** [comment]
Updated the AD001 and AD002 to handle more complex environments.  Uploading them now.

**Pull request merged**
