### PR TITLE
HW001

### PR DESCRIPTION
**Pull request by damianscoles**
This function checks to see if the Exchange Server is Physical or Virtual.

### CODE REVIEW

**Comment by swngdnz** [comment]
} elseif($virtual.Manufacturer.Length -gt 0) {  
 39   +  
 40   +            # Server is running on a Physical Server  
 41   +            $WarningList = "Physical"  
 42   +            write-verbose "The server $name is virtualized on the $Virtualtype platform."  
 43   +    

$virtualType is null (s/b $virtual.Manufacturer). $WarningList is overwritten( s/b += ).

**Comment by cunninghamp** [comment]
```
$WarningList = "Physical"
```

Yeah that looks like a typo?

**Comment by damianscoles** [comment]
Yeah, I'll put it as an Info.  I also changed the unknown to read a little better.  If the platform cannot be determined we probably cannot assume it's virtualized.

**Comment by damianscoles** [comment]
Changes complete.

**Comment by cunninghamp** [comment]
Closes #71

**Pull request merged**
